"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
[directory]
truncation_length = 5

[character]
success_symbol = '[➜](bold green)'
error_symbol = "[!](bold red)"

[git_status]
disabled = false

[git_branch]
symbol = ' '

[package]
disabled = true

# format = """
# $git_branch\
# $git_status\
# $python\
# $nodejs\
# $c\
# $rust\
# $golang\
# $line_break\
# $directory $line_break\
# $character"""
#
#
# [character]
# success_symbol = '[➜](bold green)'
# error_symbol = '[➜](bold red)'
#
#
# [time]
# format = "[$time]($style)"
# disabled = false
#
# [username]
# show_always = true
# format = "[$user]($style)"
#
# [hostname]
# ssh_only = false
# format = "[$hostname]($style)"
#
# [c]
# format = "[$symbol($version )]($style)"
# symbol = " "
#
# [directory]
# read_only = " "
#
#
# [golang]
# symbol = " "
# format = "[$symbol($version )]($style)"
#
# [hg_branch]
# symbol = " "
#
#
# [nodejs]
# format = "[$symbol($version )]($style)"
# symbol = " "
#
# [os]
# disabled = true
#
# [os.symbols]
# Linux = " "
# Macos = " "
# Ubuntu = " "
# Unknown = " "
# Windows = "󰍲 "
#
# [package]
# symbol = " "
# format = "[$symbol($version )]($style)"
#
# [python]
# symbol = " "
# format = "[$symbol($version )]($style)($virtualenv)"
