
[tool.ruff]
extend-include = ["*.ipynb"]

# ...but use a different line length.
line-length = 88


[tool.ruff.lint]
select = [
  # pycodestyle
  "E",
  # Pyflakes
  "F",
  # flake8-bugbear
  "B",
  # flake8-simplify
  #  "SIM",
  # isort
  "I",
  # Warning,
  "W",
  # pep8 naming
  "N",
  # pydoc style
  "D",
  # flake8 django
  "DJ",
  # Ruff specific
  "RUF",
  #mccabe
  "C90",
  # pyupgrade
  "UP",
  #flake8-annotations
  "ANN",
  # flake8-bandit
  "S",
  # flake8-boolean-trap
  "FBT",
  # flake8-builtins
  "A",
  # flake8-commas
  "COM",
  # flake8-comprehensions
  "C4",
  # flake8-datetimez
  "DTZ",
  # flake8-errormsg
  "EM",
  # pandas-vet
  "PD",
  "R",
  "C",
  "TRY",
  "FLY",
  "NPY",
  "PERF",
  "FURB",
]
