vim.b.slime_cell_delimiter = "#\\s\\=%%"
vim.g.autoformat = false
vim.opt_local.expandtab = true
vim.opt_local.shiftwidth = 2
vim.opt_local.tabstop = 2
vim.opt_local.conceallevel = 0
vim.opt_local.softtabstop = 2
vim.opt_local.smartindent = true
vim.opt_local.foldmethod = "indent"
